### ISSUE TITLE
greedy + sparse initialization

### ISSUE THREAD

**Issue by gregoriog** [epnev/ca_source_extraction#16] opened 2016-02-27 16:26 UTC
hello,

I am interested in extracting axonal calcium traces. 
When applying the greedy method, the program worked very well, but many boutons and axons distant from one another, but belonging to the same axon and displaying the same activity are not merged together.
When applying  the 'sparse_NMF' method, the output I get is more like of the neuropil. 
I would like to try the ‘greedy’ and ‘sparse_NMF’ methods combined (as it is stated in the documentation file) but I don't know how to proceed. Could you give me some hints? 

Best

**Comment by epnev** [comment] 2016-02-29 15:04
@gregoriog 

A thing you can try is first run the greedy method that will find the boutons and smaller components, then compute the residual  Y - Ain*Cin - bin*fin (you'll probably need to reshape your matrices back and forth to do the multiplications), and then run the initialization again with the 'sparse_NMF' method. Then combine the results, and see if the results look better. 

You can also play with the merging threshold, but bear in mind that the algorithm only merges components that are spatially overlapping. So you might want to consider to merge things manually.

Since this is not a bug related issue with the code, I'm closing this issue. Feel free to use the chat room or send me an email for additional questions.

Eftychios

**Closed by epnev** 2016-02-29 15:04 UTC

**Comment by gregoriog** [comment] 2016-02-29 15:08
Thank you for your answer Eftychios


Gregorio
d*!*b
